# Generated by Django 4.2.11 on 2024-03-21 18:55

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=tasks.models.due_time)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.todolist')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
